# The Numpy array object

# NumPy Arrays

In [1]:
import numpy as ip
a = np.array([0, 1, 2, 3])
print(a)

print(ip.arange(10))

NameError: name 'np' is not defined

# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [6]:
#1-D

a = ip.array([0, 4, 5, 14, 54, 19])

a

array([ 0,  4,  5, 14, 54, 19])

In [7]:
#print dimensions

a.ndim

1

In [8]:
#shape

a.shape

(6,)

In [ ]:
len(a)

4

In [10]:
# 2-D, 3-D....

b = ip.array([[0, 25, 12], [69, 85, 14]])

b

array([[ 0, 25, 12],
       [69, 85, 14]])

In [ ]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first dimention

2

** 1.2  Functions for creating arrays**

In [15]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = ip.arange(15) # 0.... n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
b = ip.arange(1, 15, 3) #start, end (exclusive), step

b

array([ 1,  4,  7, 10, 13])

In [25]:
#using linspace

a = ip.linspace(0, 21, 5) #start, end, number of points

a

array([ 0.  ,  5.25, 10.5 , 15.75, 21.  ])

In [26]:
#common arrays

a = ip.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
b = ip.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
c = ip.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
d = ip.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [30]:
#create array using diag function

a = ip.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
ip.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [32]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = ip.random.rand(4)

a

array([0.73787653, 0.45479222, 0.54531481, 0.15209825])

In [33]:
a = ip.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 0.42843049, -1.70031303, -2.56571033, -0.44639151])

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [34]:
a = ip.arange(10)

a.dtype

dtype('int64')

In [35]:
#You can explicitly specify which data-type you want:

a = ip.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
#The default data type is float for zeros and ones function

a = ip.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [37]:
d = ip.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [38]:
b = ip.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [39]:
a = ip.arange(10)
print(a)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

[0 1 2 3 4 5 6 7 8 9]
5


In [40]:
# For multidimensional arrays, indexes are tuples of integers:

a = ip.diag([1, 2, 3])
print(a)
print(a[2, 2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [ ]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [41]:
a = ip.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [42]:
#we can also combine assignment and slicing:

a = ip.arange(10)
print(a)
a[5:] = 10
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [43]:
b = ip.arange(5)
print(b)
a[5:] = b[::-1]  #assigning

a

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [44]:
a = ip.random.randint(0, 20, 55)
a

array([15, 17,  8, 15,  8,  0,  9,  3, 19, 19,  0,  1, 12, 11,  3,  1, 16,
       11,  4,  0,  4, 10,  2, 18, 16,  3,  1, 11,  0,  8, 18,  3, 16, 14,
        8, 15,  0,  3,  3,  7, 12,  1,  2, 18, 16,  6,  5,  3,  0, 14,  3,
       16, 14, 12,  9])

In [55]:
mask = (a % 2 == 0)

In [56]:
extract_from_a = a[mask]

extract_from_a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [57]:
a[mask] = -1
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

**Indexing with an array of integers**

In [50]:
a = ip.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])